// ==========================================
// DUNGEON FORECAST DATABASE
// Source: Narakia et Vicky Zweistein
// Range: 14/12/2025 to 09/02/2026
// ==========================================

const FORECAST_DB = {
    "14/12/2025": [
        { "type": "DJ 6 - 20", "name": "Pâturages des Bouftous" },
        { "type": "DJ 21 - 35", "name": "Le Caveau Relevé" },
        { "type": "DJ 36 - 50", "name": "Les Champs Pourchan" },
        { "type": "DJ 51 - 65", "name": "Tour des Miss Moches" },
        { "type": "DJ 66 - 80", "name": "Palais du Tsu" },
        { "type": "DJ 81 - 95", "name": "Sliptorium" },
        { "type": "DJ 96 - 110", "name": "Donjon Gelée" },
        { "type": "DJ 111 - 125", "name": "Fosse du Tourmenteur" },
        { "type": "DJ 126 - 140", "name": "Compost du grand Potofeu" },
        { "type": "DJ 141 - 155", "name": "Donjon Srambad" },
        { "type": "DJ 156 - 170", "name": "Roub'Bar" },
        { "type": "DJ 171 - 185", "name": "Donjon Gerbouille" },
        { "type": "DJ 186 - 200", "name": "La Crête Givrée" },
        { "type": "DJ 201 - 215", "name": "Donjon Toundrasoirs" },
        { "type": "DJ 216 - 230", "name": "Donjon Égarés ?" },
        { "type": "DJ 231 - 245", "name": "Donjon Égarés ?" },
        { "type": "Modulox 6 - 50", "name": "La Tour Minérale" },
        { "type": "Modulox 51 - 95", "name": "La Corbeau-Cave" },
        { "type": "Modulox 96 - 140", "name": "Aile de l'Ambassadrice" },
        { "type": "Modulox 141 - 185", "name": "Donjon Riktus Elite" },
        { "type": "Modulox 186 - 230", "name": "Donjon Toundrasoirs" }
    ],
    "15/12/2025": [
        { "type": "DJ 6 - 20", "name": "Le Tofulailler" },
        { "type": "DJ 21 - 35", "name": "Piou Lahoupe" },
        { "type": "DJ 36 - 50", "name": "Donjon Mort-Brûlés" },
        { "type": "DJ 51 - 65", "name": "Donjon Bwork" },
        { "type": "DJ 66 - 80", "name": "Truchière Abandonnée" },
        { "type": "DJ 81 - 95", "name": "Château de Wagnar" },
        { "type": "DJ 96 - 110", "name": "Repaire des Magik Riktus" },
        { "type": "DJ 111 - 125", "name": "La Pichine" },
        { "type": "DJ 126 - 140", "name": "Sanctuaire de Mihmol" },
        { "type": "DJ 141 - 155", "name": "Château du Wa Wabbit" },
        { "type": "DJ 156 - 170", "name": "Donjon E-Bou" },
        { "type": "DJ 171 - 185", "name": "Donjon des Crocodailles" },
        { "type": "DJ 186 - 200", "name": "La Tour Minérale Elite (lvl 200)" },
        { "type": "DJ 201 - 215", "name": "Donjon Carapattes" },
        { "type": "DJ 216 - 230", "name": "Donjon Ravageurs" },
        { "type": "DJ 231 - 245", "name": "Donjon Ravageurs" },
        { "type": "Modulox 6 - 50", "name": "Le Tofulailler" },
        { "type": "Modulox 51 - 95", "name": "Kokokolantha" },
        { "type": "Modulox 96 - 140", "name": "Niche du Yech'Ti'Wawa" },
        { "type": "Modulox 141 - 185", "name": "Donjon des Tropikes" },
        { "type": "Modulox 186 - 230", "name": "Usine Hibourg" }
    ],
    "16/12/2025": [
        { "type": "DJ 6 - 20", "name": "The Tofuhouse" },
        { "type": "DJ 21 - 35", "name": "Treechnee Dungeon" },
        { "type": "DJ 36 - 50", "name": "The Mineral Tower" },
        { "type": "DJ 51 - 65", "name": "Mollusky Dungeon" },
        { "type": "DJ 66 - 80", "name": "Arachnee Dungeon" },
        { "type": "DJ 81 - 95", "name": "The Undieworld" },
        { "type": "DJ 96 - 110", "name": "Dancehall Arena" },
        { "type": "DJ 111 - 125", "name": "Ambassador's Wing" },
        { "type": "DJ 126 - 140", "name": "Treechnid Dungeon" },
        { "type": "DJ 141 - 155", "name": "Enurado Dungeon" },
        { "type": "DJ 156 - 170", "name": "Elite Riktus Dungeon" },
        { "type": "DJ 171 - 185", "name": "Forbidden City" },
        { "type": "DJ 186 - 200", "name": "Pandala Tomb" },
        { "type": "DJ 201 - 215", "name": "Pingwin Dungeon" },
        { "type": "DJ 216 - 230", "name": "Foggernaut Dungeon" },
        { "type": "DJ 231 - 245", "name": "Bworkana Clan Dungeon" },
        { "type": "Modulox 6 - 50", "name": "The Raised Vault" },
        { "type": "Modulox 51 - 95", "name": "Morbax Neplopolis" },
        { "type": "Modulox 96 - 140", "name": "The Whirlway Station" },
        { "type": "Modulox 141 - 185", "name": "Forbidden City" },
        { "type": "Modulox 186 - 230", "name": "Streye Dungeon?" }
    ],
    "17/12/2025": [
        { "type": "DJ 6 - 20", "name": "Gobball Pastures" },
        { "type": "DJ 21 - 35", "name": "The Raised Vault" },
        { "type": "DJ 36 - 50", "name": "The Hill Hazize" },
        { "type": "DJ 51 - 65", "name": "Miss Ugly Tower" },
        { "type": "DJ 66 - 80", "name": "Cro-Cave" },
        { "type": "DJ 81 - 95", "name": "Miseryum" },
        { "type": "DJ 96 - 110", "name": "Hushquarters" },
        { "type": "DJ 111 - 125", "name": "The Whirlway Station" },
        { "type": "DJ 126 - 140", "name": "Lenald Empelol's Temple" },
        { "type": "DJ 141 - 155", "name": "Wellspring of Evil" },
        { "type": "DJ 156 - 170", "name": "The Zeppelantern" },
        { "type": "DJ 171 - 185", "name": "Kannivore Dungeon" },
        { "type": "DJ 186 - 200", "name": "Bubourg Factory" },
        { "type": "DJ 201 - 215", "name": "The Mineral Tower (lvl 215)" },
        { "type": "DJ 216 - 230", "name": "Necroworld" },
        { "type": "DJ 231 - 245", "name": "Nox Machine Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Treechnee Dungeon" },
        { "type": "Modulox 51 - 95", "name": "The Forgotten Lair" },
        { "type": "Modulox 96 - 140", "name": "Jelly Dungeon" },
        { "type": "Modulox 141 - 185", "name": "Sandyoptera Mother-Hive" },
        { "type": "Modulox 186 - 230", "name": "Dreggons' Sanctuary" }
    ],
    "18/12/2025": [
        { "type": "DJ 6 - 20", "name": "Gobball Pastures" },
        { "type": "DJ 21 - 35", "name": "Hoola Hoopiwi" },
        { "type": "DJ 36 - 50", "name": "Sureberry Fields" },
        { "type": "DJ 51 - 65", "name": "Kokokobana" },
        { "type": "DJ 66 - 80", "name": "Boarthroom Estate" },
        { "type": "DJ 81 - 95", "name": "Abandoned Scarapit" },
        { "type": "DJ 96 - 110", "name": "Moowolf's Lair" },
        { "type": "DJ 111 - 125", "name": "Puddly Dungeon" },
        { "type": "DJ 126 - 140", "name": "Kween's Gawden" },
        { "type": "DJ 141 - 155", "name": "SrambadDungeon" },
        { "type": "DJ 156 - 170", "name": "The Stalagmotel" },
        { "type": "DJ 171 - 185", "name": "Tropickle Dungeon" },
        { "type": "DJ 186 - 200", "name": "Badgeroxes' Lair" },
        { "type": "DJ 201 - 215", "name": "Vandalophrenic Dungeon" },
        { "type": "DJ 216 - 230", "name": "Phytomorph Dungeon" },
        { "type": "DJ 231 - 245", "name": "Bworkana Clan Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Deathburn Dungeon" },
        { "type": "Modulox 51 - 95", "name": "Abandoned Strichery" },
        { "type": "Modulox 96 - 140", "name": "Treechnid Dungeon" },
        { "type": "Modulox 141 - 185", "name": "Kanniball Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Blightopard Canyon" }
    ],
    "19/12/2025": [
        { "type": "DJ 6 - 20", "name": "The Tofuhouse" },
        { "type": "DJ 21 - 35", "name": "The Raised Vault" },
        { "type": "DJ 36 - 50", "name": "Octopus Crew Dungeon" },
        { "type": "DJ 51 - 65", "name": "Dry Selachii" },
        { "type": "DJ 66 - 80", "name": "Tsu's Palace" },
        { "type": "DJ 81 - 95", "name": "Mussly Hammam" },
        { "type": "DJ 96 - 110", "name": "The Horned Glacier" },
        { "type": "DJ 111 - 125", "name": "Tormentor Pit" },
        { "type": "DJ 126 - 140", "name": "Blackspore Dungeon" },
        { "type": "DJ 141 - 155", "name": "Abandoned Cawwot Stowewoom" },
        { "type": "DJ 156 - 170", "name": "Mecha Factory" },
        { "type": "DJ 171 - 185", "name": "Kanniball Dungeon" },
        { "type": "DJ 186 - 200", "name": "Blightopard Canyon" },
        { "type": "DJ 201 - 215", "name": "Plantiguard Dungeon" },
        { "type": "DJ 216 - 230", "name": "Abyssal Creeper Dungeon" },
        { "type": "DJ 231 - 245", "name": "Timeless Theater Dungeon" },
        { "type": "Modulox 6 - 50", "name": "The Raised Vault" },
        { "type": "Modulox 51 - 95", "name": "Dry Selachii" },
        { "type": "Modulox 96 - 140", "name": "Puddly Dungeon" },
        { "type": "Modulox 141 - 185", "name": "Ow El Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Pandala Tomb" }
    ],
    "20/12/2025": [
        { "type": "DJ 6 - 20", "name": "Larventura" },
        { "type": "DJ 21 - 35", "name": "Treechnee Dungeon" },
        { "type": "DJ 36 - 50", "name": "The Mineral Tower" },
        { "type": "DJ 51 - 65", "name": "Kokokobana" },
        { "type": "DJ 66 - 80", "name": "Arachnee Dungeon" },
        { "type": "DJ 81 - 95", "name": "Schnekymosis Cavern" },
        { "type": "DJ 96 - 110", "name": "Dancehall Arena" },
        { "type": "DJ 111 - 125", "name": "Hagen Daz's Pot" },
        { "type": "DJ 126 - 140", "name": "Treechnid Dungeon" },
        { "type": "DJ 141 - 155", "name": "The Villainy Vineyards" },
        { "type": "DJ 156 - 170", "name": "Elite Riktus Dungeon" },
        { "type": "DJ 171 - 185", "name": "Forbidden City" },
        { "type": "DJ 186 - 200", "name": "Badgeroxes' Lair" },
        { "type": "DJ 201 - 215", "name": "Vandalophrenic Dungeon" },
        { "type": "DJ 216 - 230", "name": "Phytomorph Dungeon" },
        { "type": "DJ 231 - 245", "name": "Ferociraptor Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Larventura" },
        { "type": "Modulox 51 - 95", "name": "Temple of the Grand Orrok" },
        { "type": "Modulox 96 - 140", "name": "The Frozen Tower" },
        { "type": "Modulox 141 - 185", "name": "Tropickle Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Voidivion Dungeon" }
    ],
    "21/12/2025": [
        { "type": "DJ 6 - 20", "name": "Gobball Pastures" },
        { "type": "DJ 21 - 35", "name": "Hoola Hoopiwi" },
        { "type": "DJ 36 - 50", "name": "The Hill Hazize" },
        { "type": "DJ 51 - 65", "name": "Miss Ugly Tower" },
        { "type": "DJ 66 - 80", "name": "Temple of the Grand Orrok" },
        { "type": "DJ 81 - 95", "name": "Trool Academy" },
        { "type": "DJ 96 - 110", "name": "Supervillains' Lair" },
        { "type": "DJ 111 - 125", "name": "Castuc Dungeon" },
        { "type": "DJ 126 - 140", "name": "Dirty Trouffe Estate" },
        { "type": "DJ 141 - 155", "name": "Blopera" },
        { "type": "DJ 156 - 170", "name": "Kali's Lair" },
        { "type": "DJ 171 - 185", "name": "Crocodyl Dungeon" },
        { "type": "DJ 186 - 200", "name": "Bubourg Factory" },
        { "type": "DJ 201 - 215", "name": "The Mineral Tower (lvl 215)" },
        { "type": "DJ 216 - 230", "name": "Necroworld" },
        { "type": "DJ 231 - 245", "name": "Primount Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Gobball Pastures" },
        { "type": "Modulox 51 - 95", "name": "Bitter-Hammer Dungeon" },
        { "type": "Modulox 96 - 140", "name": "The Horned Glacier" },
        { "type": "Modulox 141 - 185", "name": "Wa Wabbit's Castle" },
        { "type": "Modulox 186 - 230", "name": "Bubourg Factory" }
    ],
    "22/12/2025": [
        { "type": "DJ 6 - 20", "name": "The Tofuhouse" },
        { "type": "DJ 21 - 35", "name": "Treechnee Dungeon" },
        { "type": "DJ 36 - 50", "name": "The Royal Pasturizer" },
        { "type": "DJ 51 - 65", "name": "Bwork Dungeon" },
        { "type": "DJ 66 - 80", "name": "Temple of the Grand Orrok" },
        { "type": "DJ 81 - 95", "name": "Morbax Neplopolis" },
        { "type": "DJ 96 - 110", "name": "Hushquarters" },
        { "type": "DJ 111 - 125", "name": "The Snaptrap" },
        { "type": "DJ 126 - 140", "name": "Lenald Empelol's Temple" },
        { "type": "DJ 141 - 155", "name": "Abandoned Cawwot Stowewoom" },
        { "type": "DJ 156 - 170", "name": "The Zeppelantern" },
        { "type": "DJ 171 - 185", "name": "Tropickle Dungeon" },
        { "type": "DJ 186 - 200", "name": "Dreggons' Sanctuary" },
        { "type": "DJ 201 - 215", "name": "Crabstacean Dungeon" },
        { "type": "DJ 216 - 230", "name": "Horridemon Dungeon" },
        { "type": "DJ 231 - 245", "name": "Starvannah Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Hoola Hoopiwi" },
        { "type": "Modulox 51 - 95", "name": "Wagnar's Castle" },
        { "type": "Modulox 96 - 140", "name": "Castuc Dungeon" },
        { "type": "Modulox 141 - 185", "name": "Gerbean Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Badgeroxes' Lair" }
    ],
    "23/12/2025": [
        { "type": "DJ 6 - 20", "name": "??" },
        { "type": "DJ 21 - 35", "name": "The Raised Vault" },
        { "type": "DJ 36 - 50", "name": "The Mineral Tower" },
        { "type": "DJ 51 - 65", "name": "Bitter-Hammer Dungeon" },
        { "type": "DJ 66 - 80", "name": "Lunar Altar" },
        { "type": "DJ 81 - 95", "name": "Abandoned Scarapit" },
        { "type": "DJ 96 - 110", "name": "Moowolf's Lair" },
        { "type": "DJ 111 - 125", "name": "The Frozen Tower" },
        { "type": "DJ 126 - 140", "name": "Kween's Gawden" },
        { "type": "DJ 141 - 155", "name": "Enurado Dungeon" },
        { "type": "DJ 156 - 170", "name": "The Stalagmotel" },
        { "type": "DJ 171 - 185", "name": "Gerbean Dungeon" },
        { "type": "DJ 186 - 200", "name": "Iced-Over Crest" },
        { "type": "DJ 201 - 215", "name": "Tundrazor Dungeon" },
        { "type": "DJ 216 - 230", "name": "Streye Dungeon?" },
        { "type": "DJ 231 - 245", "name": "Nox Machine Dungeon" },
        { "type": "Modulox 6 - 50", "name": "The Royal Pasturizer" },
        { "type": "Modulox 51 - 95", "name": "Tsu's Palace" },
        { "type": "Modulox 96 - 140", "name": "Dancehall Arena" },
        { "type": "Modulox 141 - 185", "name": "Crocodyl Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Pandala Tomb" }
    ],
    "24/12/2025": [
        { "type": "DJ 6 - 20", "name": "Larventura" },
        { "type": "DJ 21 - 35", "name": "Hoola Hoopiwi" },
        { "type": "DJ 36 - 50", "name": "The Hill Hazize" },
        { "type": "DJ 51 - 65", "name": "The Forgotten Lair" },
        { "type": "DJ 66 - 80", "name": "Abandoned Strichery" },
        { "type": "DJ 81 - 95", "name": "Miseryum" },
        { "type": "DJ 96 - 110", "name": "The Horned Glacier" },
        { "type": "DJ 111 - 125", "name": "Ambassador's Wing" },
        { "type": "DJ 126 - 140", "name": "Blackspore Dungeon" },
        { "type": "DJ 141 - 155", "name": "Sandyoptera Mother-Hive" },
        { "type": "DJ 156 - 170", "name": "Mecha Factory" },
        { "type": "DJ 171 - 185", "name": "Kanniball Dungeon" },
        { "type": "DJ 186 - 200", "name": "Or'Hodruin Volcano" },
        { "type": "DJ 201 - 215", "name": "Sunsloth Dungeon" },
        { "type": "DJ 216 - 230", "name": "Voidivion Dungeon" },
        { "type": "DJ 231 - 245", "name": "Timeless Theater Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Treechnid Dungeon" },
        { "type": "Modulox 51 - 95", "name": "Cwab's Castle" },
        { "type": "Modulox 96 - 140", "name": "The Frozen Tower" },
        { "type": "Modulox 141 - 185", "name": "Blopera" },
        { "type": "Modulox 186 - 230", "name": "Scramshell Dungeon" }
    ],
    "25/12/2025": [
        { "type": "DJ 6 - 20", "name": "The Tofuhouse" },
        { "type": "DJ 21 - 35", "name": "Treechnee Dungeon" },
        { "type": "DJ 36 - 50", "name": "Octopus Crew Dungeon" },
        { "type": "DJ 51 - 65", "name": "Cwab's Castle" },
        { "type": "DJ 66 - 80", "name": "The Ratatombs" },
        { "type": "DJ 81 - 95", "name": "Schnekymosis Cavern" },
        { "type": "DJ 96 - 110", "name": "Jelly Dungeon" },
        { "type": "DJ 111 - 125", "name": "Puddly Dungeon" },
        { "type": "DJ 126 - 140", "name": "Great Zomkin's Compost" },
        { "type": "DJ 141 - 155", "name": "Wellspring of Evil" },
        { "type": "DJ 156 - 170", "name": "Elite Riktus Dungeon" },
        { "type": "DJ 171 - 185", "name": "Tropickle Dungeon" },
        { "type": "DJ 186 - 200", "name": "The Minerall Tower (lvl 200)" },
        { "type": "DJ 201 - 215", "name": "Scramshell Dungeon" },
        { "type": "DJ 216 - 230", "name": "Destroyer Dungeon" },
        { "type": "DJ 231 - 245", "name": "Starvannah Dungeon" },
        { "type": "Modulox 6 - 50", "name": "The Raised Vault" },
        { "type": "Modulox 51 - 95", "name": "Arachnee Dungeon" },
        { "type": "Modulox 96 - 140", "name": "Hagen Daz's Pot" },
        { "type": "Modulox 141 - 185", "name": "SrambadDungeon" },
        { "type": "Modulox 186 - 230", "name": "Or'Hodruin Volcano" }
    ],
    "26/12/2025": [
        { "type": "DJ 6 - 20", "name": "Gobball Pastures" },
        { "type": "DJ 21 - 35", "name": "The Raised Vault" },
        { "type": "DJ 36 - 50", "name": "Deathburn Dungeon" },
        { "type": "DJ 51 - 65", "name": "Mollusky Dungeon" },
        { "type": "DJ 66 - 80", "name": "Lunar Altar" },
        { "type": "DJ 81 - 95", "name": "Mussly Hammam" },
        { "type": "DJ 96 - 110", "name": "Magik Riktus Den" },
        { "type": "DJ 111 - 125", "name": "The Snaptrap" },
        { "type": "DJ 126 - 140", "name": "Flaxhid's Sanctuary" },
        { "type": "DJ 141 - 155", "name": "Wa Wabbit's Castle" },
        { "type": "DJ 156 - 170", "name": "The Zeppelantern" },
        { "type": "DJ 171 - 185", "name": "Kannivore Dungeon" },
        { "type": "DJ 186 - 200", "name": "Pandala Tomb" },
        { "type": "DJ 201 - 215", "name": "Pingwin Dungeon" },
        { "type": "DJ 216 - 230", "name": "Foggernaut Dungeon" },
        { "type": "DJ 231 - 245", "name": "Primount Dungeon" },
        { "type": "Modulox 6 - 50", "name": "The Hill Hazize" },
        { "type": "Modulox 51 - 95", "name": "Miseryum" },
        { "type": "Modulox 96 - 140", "name": "Magik Riktus Den" },
        { "type": "Modulox 141 - 185", "name": "Enurado Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Plantiguard Dungeon" }
    ],
    "27/12/2025": [
        { "type": "DJ 6 - 20", "name": "Gobball Pastures" },
        { "type": "DJ 21 - 35", "name": "Hoola Hoopiwi" },
        { "type": "DJ 36 - 50", "name": "The Royal Pasturizer" },
        { "type": "DJ 51 - 65", "name": "Bwork Dungeon" },
        { "type": "DJ 66 - 80", "name": "Boarthroom Estate" },
        { "type": "DJ 81 - 95", "name": "The Undieworld" },
        { "type": "DJ 96 - 110", "name": "Hushquarters" },
        { "type": "DJ 111 - 125", "name": "Tormentor Pit" },
        { "type": "DJ 126 - 140", "name": "Lenald Empelol's Temple" },
        { "type": "DJ 141 - 155", "name": "Blopera" },
        { "type": "DJ 156 - 170", "name": "The Stalagmotel" },
        { "type": "DJ 171 - 185", "name": "Crocodyl Dungeon" },
        { "type": "DJ 186 - 200", "name": "Dreggons' Sanctuary" },
        { "type": "DJ 201 - 215", "name": "Crabstacean Dungeon" },
        { "type": "DJ 216 - 230", "name": "Horridemon Dungeon" },
        { "type": "DJ 231 - 245", "name": "Ferociraptor Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Sureberry Fields" },
        { "type": "Modulox 51 - 95", "name": "Mollusky Dungeon" },
        { "type": "Modulox 96 - 140", "name": "Tormentor Pit" },
        { "type": "Modulox 141 - 185", "name": "The Stalagmotel" },
        { "type": "Modulox 186 - 230", "name": "Destroyer Dungeon" }
    ],
    "28/12/2025": [
        { "type": "DJ 6 - 20", "name": "The Tofuhouse" },
        { "type": "DJ 21 - 35", "name": "The Raised Vault" },
        { "type": "DJ 36 - 50", "name": "Sureberry Fields" },
        { "type": "DJ 51 - 65", "name": "Dry Selachii" },
        { "type": "DJ 66 - 80", "name": "Cro-Cave" },
        { "type": "DJ 81 - 95", "name": "Morbax Neplopolis" },
        { "type": "DJ 96 - 110", "name": "Supervillains' Lair" },
        { "type": "DJ 111 - 125", "name": "Castuc Dungeon" },
        { "type": "DJ 126 - 140", "name": "Dirty Trouffe Estate" },
        { "type": "DJ 141 - 155", "name": "SrambadDungeon" },
        { "type": "DJ 156 - 170", "name": "Mecha Factory" },
        { "type": "DJ 171 - 185", "name": "Kanniball Dungeon" },
        { "type": "DJ 186 - 200", "name": "Blightopard Canyon" },
        { "type": "DJ 201 - 215", "name": "Plantiguard Dungeon" },
        { "type": "DJ 216 - 230", "name": "Abyssal Creeper Dungeon" },
        { "type": "DJ 231 - 245", "name": "Timeless Theater Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Deathburn Dungeon" },
        { "type": "Modulox 51 - 95", "name": "Abandoned Strichery" },
        { "type": "Modulox 96 - 140", "name": "Flaxhid's Sanctuary" },
        { "type": "Modulox 141 - 185", "name": "Abandoned Cawwot Stowewoom" },
        { "type": "Modulox 186 - 230", "name": "Phytomorph Dungeon" }
    ],
    "29/12/2025": [
        { "type": "DJ 6 - 20", "name": "Larventura" },
        { "type": "DJ 21 - 35", "name": "Treechnee Dungeon" },
        { "type": "DJ 36 - 50", "name": "Octopus Crew Dungeon" },
        { "type": "DJ 51 - 65", "name": "Bitter-Hammer Dungeon" },
        { "type": "DJ 66 - 80", "name": "Arachnee Dungeon" },
        { "type": "DJ 81 - 95", "name": "Trool Academy" },
        { "type": "DJ 96 - 110", "name": "Jelly Dungeon" },
        { "type": "DJ 111 - 125", "name": "Hagen Daz's Pot" },
        { "type": "DJ 126 - 140", "name": "Great Zomkin's Compost" },
        { "type": "DJ 141 - 155", "name": "Abandoned Cawwot Stowewoom" },
        { "type": "DJ 156 - 170", "name": "Elite Riktus Dungeon" },
        { "type": "DJ 171 - 185", "name": "Forbidden City" },
        { "type": "DJ 186 - 200", "name": "Iced-Over Crest" },
        { "type": "DJ 201 - 215", "name": "Tundrazor Dungeon" },
        { "type": "DJ 216 - 230", "name": "Streye Dungeon?" },
        { "type": "DJ 231 - 245", "name": "Starvannah Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Larventura" },
        { "type": "Modulox 51 - 95", "name": "Morbax Neplopolis" },
        { "type": "Modulox 96 - 140", "name": "Hushquarters" },
        { "type": "Modulox 141 - 185", "name": "The Villainy Vineyards" },
        { "type": "Modulox 186 - 230", "name": "The Minerall Tower (lvl 200)" }
    ],
    "30/12/2025": [
        { "type": "DJ 6 - 20", "name": "Gobball Pastures" },
        { "type": "DJ 21 - 35", "name": "Hoola Hoopiwi" },
        { "type": "DJ 36 - 50", "name": "The Royal Pasturizer" },
        { "type": "DJ 51 - 65", "name": "The Forgotten Lair" },
        { "type": "DJ 66 - 80", "name": "The Ratatombs" },
        { "type": "DJ 81 - 95", "name": "Wagnar's Castle" },
        { "type": "DJ 96 - 110", "name": "Moowolf's Lair" },
        { "type": "DJ 111 - 125", "name": "The Whirlway Station" },
        { "type": "DJ 126 - 140", "name": "Kween's Gawden" },
        { "type": "DJ 141 - 155", "name": "The Villainy Vineyards" },
        { "type": "DJ 156 - 170", "name": "Kali's Lair" },
        { "type": "DJ 171 - 185", "name": "Gerbean Dungeon" },
        { "type": "DJ 186 - 200", "name": "Or'Hodruin Volcano" },
        { "type": "DJ 201 - 215", "name": "Sunsloth Dungeon" },
        { "type": "DJ 216 - 230", "name": "Voidivion Dungeon" },
        { "type": "DJ 231 - 245", "name": "Ferociraptor Dungeon" },
        { "type": "Modulox 6 - 50", "name": "The Mineral Tower" },
        { "type": "Modulox 51 - 95", "name": "The Forgotten Lair" },
        { "type": "Modulox 96 - 140", "name": "Kween's Gawden" },
        { "type": "Modulox 141 - 185", "name": "Wa Wabbit's Castle" },
        { "type": "Modulox 186 - 230", "name": "Sunsloth Dungeon" }
    ],
    "31/12/2025": [
        { "type": "DJ 6 - 20", "name": "The Tofuhouse" },
        { "type": "DJ 21 - 35", "name": "Treechnee Dungeon" },
        { "type": "DJ 36 - 50", "name": "Deathburn Dungeon" },
        { "type": "DJ 51 - 65", "name": "Miss Ugly Tower" },
        { "type": "DJ 66 - 80", "name": "Tsu's Palace" },
        { "type": "DJ 81 - 95", "name": "Abandoned Scarapit" },
        { "type": "DJ 96 - 110", "name": "Magik Riktus Den" },
        { "type": "DJ 111 - 125", "name": "The Frozen Tower" },
        { "type": "DJ 126 - 140", "name": "Flaxhid's Sanctuary" },
        { "type": "DJ 141 - 155", "name": "Sandyoptera Mother-Hive" },
        { "type": "DJ 156 - 170", "name": "The Zeppelantern" },
        { "type": "DJ 171 - 185", "name": "Kannivore Dungeon" },
        { "type": "DJ 186 - 200", "name": "Bubourg Factory" },
        { "type": "DJ 201 - 215", "name": "The Mineral Tower (lvl 215)" },
        { "type": "DJ 216 - 230", "name": "Necroworld" },
        { "type": "DJ 231 - 245", "name": "Nox Machine Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Octopus Crew Dungeon" },
        { "type": "Modulox 51 - 95", "name": "Wagnar's Castle" },
        { "type": "Modulox 96 - 140", "name": "Ambassador's Wing" },
        { "type": "Modulox 141 - 185", "name": "Sandyoptera Mother-Hive" },
        { "type": "Modulox 186 - 230", "name": "Crabstacean Dungeon" }
    ],
    "01/01/2026": [
        { "type": "DJ 6 - 20", "name": "??" },
        { "type": "DJ 21 - 35", "name": "The Raised Vault" },
        { "type": "DJ 36 - 50", "name": "Sureberry Fields" },
        { "type": "DJ 51 - 65", "name": "Bwork Dungeon" },
        { "type": "DJ 66 - 80", "name": "Abandoned Strichery" },
        { "type": "DJ 81 - 95", "name": "Miseryum" },
        { "type": "DJ 96 - 110", "name": "Dancehall Arena" },
        { "type": "DJ 111 - 125", "name": "The Whirlway Station" },
        { "type": "DJ 126 - 140", "name": "Treechnid Dungeon" },
        { "type": "DJ 141 - 155", "name": "Enurado Dungeon" },
        { "type": "DJ 156 - 170", "name": "The Stalagmotel" },
        { "type": "DJ 171 - 185", "name": "Gerbean Dungeon" },
        { "type": "DJ 186 - 200", "name": "Dreggons' Sanctuary" },
        { "type": "DJ 201 - 215", "name": "Crabstacean Dungeon" },
        { "type": "DJ 216 - 230", "name": "Horridemon Dungeon" },
        { "type": "DJ 231 - 245", "name": "Bworkana Clan Dungeon" },
        { "type": "Modulox 6 - 50", "name": "The Hill Hazize" },
        { "type": "Modulox 51 - 95", "name": "Boarthroom Estate" },
        { "type": "Modulox 96 - 140", "name": "Blackspore Dungeon" },
        { "type": "Modulox 141 - 185", "name": "Kannivore Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Pingwin Dungeon" }
    ],
    "02/01/2026": [
        { "type": "DJ 6 - 20", "name": "Larventura" },
        { "type": "DJ 21 - 35", "name": "Hoola Hoopiwi" },
        { "type": "DJ 36 - 50", "name": "Deathburn Dungeon" },
        { "type": "DJ 51 - 65", "name": "Kokokobana" },
        { "type": "DJ 66 - 80", "name": "Temple of the Grand Orrok" },
        { "type": "DJ 81 - 95", "name": "Wagnar's Castle" },
        { "type": "DJ 96 - 110", "name": "Supervillains' Lair" },
        { "type": "DJ 111 - 125", "name": "Hagen Daz's Pot" },
        { "type": "DJ 126 - 140", "name": "Dirty Trouffe Estate" },
        { "type": "DJ 141 - 155", "name": "Wellspring of Evil" },
        { "type": "DJ 156 - 170", "name": "Mecha Factory" },
        { "type": "DJ 171 - 185", "name": "Crocodyl Dungeon" },
        { "type": "DJ 186 - 200", "name": "Badgeroxes' Lair" },
        { "type": "DJ 201 - 215", "name": "Vandalophrenic Dungeon" },
        { "type": "DJ 216 - 230", "name": "Phytomorph Dungeon" },
        { "type": "DJ 231 - 245", "name": "Primount Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Hoola Hoopiwi" },
        { "type": "Modulox 51 - 95", "name": "Cro-Cave" },
        { "type": "Modulox 96 - 140", "name": "The Snaptrap" },
        { "type": "Modulox 141 - 185", "name": "Kanniball Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Sunsloth Dungeon" }
    ],
    "03/01/2026": [
        { "type": "DJ 6 - 20", "name": "The Tofuhouse" },
        { "type": "DJ 21 - 35", "name": "Treechnee Dungeon" },
        { "type": "DJ 36 - 50", "name": "The Mineral Tower" },
        { "type": "DJ 51 - 65", "name": "Cwab's Castle" },
        { "type": "DJ 66 - 80", "name": "Lunar Altar" },
        { "type": "DJ 81 - 95", "name": "Schnekymosis Cavern" },
        { "type": "DJ 96 - 110", "name": "The Horned Glacier" },
        { "type": "DJ 111 - 125", "name": "The Frozen Tower" },
        { "type": "DJ 126 - 140", "name": "Blackspore Dungeon" },
        { "type": "DJ 141 - 155", "name": "Wa Wabbit's Castle" },
        { "type": "DJ 156 - 170", "name": "Elite Riktus Dungeon" },
        { "type": "DJ 171 - 185", "name": "Forbidden City" },
        { "type": "DJ 186 - 200", "name": "The Minerall Tower (lvl 200)" },
        { "type": "DJ 201 - 215", "name": "Scramshell Dungeon" },
        { "type": "DJ 216 - 230", "name": "Destroyer Dungeon" },
        { "type": "DJ 231 - 245", "name": "Bworkana Clan Dungeon" },
        { "type": "Modulox 6 - 50", "name": "The Tofuhouse" },
        { "type": "Modulox 51 - 95", "name": "Abandoned Strichery" },
        { "type": "Modulox 96 - 140", "name": "Treechnid Dungeon" },
        { "type": "Modulox 141 - 185", "name": "Kali's Lair" },
        { "type": "Modulox 186 - 230", "name": "Horridemon Dungeon" }
    ],
    "04/01/2026": [
        { "type": "DJ 6 - 20", "name": "Gobball Pastures" },
        { "type": "DJ 21 - 35", "name": "The Raised Vault" },
        { "type": "DJ 36 - 50", "name": "The Hill Hazize" },
        { "type": "DJ 51 - 65", "name": "Mollusky Dungeon" },
        { "type": "DJ 66 - 80", "name": "The Ratatombs" },
        { "type": "DJ 81 - 95", "name": "Mussly Hammam" },
        { "type": "DJ 96 - 110", "name": "Jelly Dungeon" },
        { "type": "DJ 111 - 125", "name": "Puddly Dungeon" },
        { "type": "DJ 126 - 140", "name": "Great Zomkin's Compost" },
        { "type": "DJ 141 - 155", "name": "Blopera" },
        { "type": "DJ 156 - 170", "name": "Kali's Lair" },
        { "type": "DJ 171 - 185", "name": "Kannivore Dungeon" },
        { "type": "DJ 186 - 200", "name": "Pandala Tomb" },
        { "type": "DJ 201 - 215", "name": "Pingwin Dungeon" },
        { "type": "DJ 216 - 230", "name": "Foggernaut Dungeon" },
        { "type": "DJ 231 - 245", "name": "Nox Machine Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Gobball Pastures" },
        { "type": "Modulox 51 - 95", "name": "Kokokobana" },
        { "type": "Modulox 96 - 140", "name": "Dirty Trouffe Estate" },
        { "type": "Modulox 141 - 185", "name": "Wellspring of Evil" },
        { "type": "Modulox 186 - 230", "name": "Abyssal Creeper Dungeon" }
    ],
    "05/01/2026": [
        { "type": "DJ 6 - 20", "name": "Gobball Pastures" },
        { "type": "DJ 21 - 35", "name": "Hoola Hoopiwi" },
        { "type": "DJ 36 - 50", "name": "The Royal Pasturizer" },
        { "type": "DJ 51 - 65", "name": "The Forgotten Lair" },
        { "type": "DJ 66 - 80", "name": "Cro-Cave" },
        { "type": "DJ 81 - 95", "name": "Morbax Neplopolis" },
        { "type": "DJ 96 - 110", "name": "Magik Riktus Den" },
        { "type": "DJ 111 - 125", "name": "Ambassador's Wing" },
        { "type": "DJ 126 - 140", "name": "Flaxhid's Sanctuary" },
        { "type": "DJ 141 - 155", "name": "The Villainy Vineyards" },
        { "type": "DJ 156 - 170", "name": "The Zeppelantern" },
        { "type": "DJ 171 - 185", "name": "Tropickle Dungeon" },
        { "type": "DJ 186 - 200", "name": "Or'Hodruin Volcano" },
        { "type": "DJ 201 - 215", "name": "Sunsloth Dungeon" },
        { "type": "DJ 216 - 230", "name": "Voidivion Dungeon" },
        { "type": "DJ 231 - 245", "name": "Bworkana Clan Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Sureberry Fields" },
        { "type": "Modulox 51 - 95", "name": "Abandoned Scarapit" },
        { "type": "Modulox 96 - 140", "name": "Hushquarters" },
        { "type": "Modulox 141 - 185", "name": "The Stalagmotel" },
        { "type": "Modulox 186 - 230", "name": "Voidivion Dungeon" }
    ],
    "06/01/2026": [
        { "type": "DJ 6 - 20", "name": "The Tofuhouse" },
        { "type": "DJ 21 - 35", "name": "Treechnee Dungeon" },
        { "type": "DJ 36 - 50", "name": "The Mineral Tower" },
        { "type": "DJ 51 - 65", "name": "Dry Selachii" },
        { "type": "DJ 66 - 80", "name": "Boarthroom Estate" },
        { "type": "DJ 81 - 95", "name": "Trool Academy" },
        { "type": "DJ 96 - 110", "name": "Hushquarters" },
        { "type": "DJ 111 - 125", "name": "Castuc Dungeon" },
        { "type": "DJ 126 - 140", "name": "Lenald Empelol's Temple" },
        { "type": "DJ 141 - 155", "name": "Sandyoptera Mother-Hive" },
        { "type": "DJ 156 - 170", "name": "The Stalagmotel" },
        { "type": "DJ 171 - 185", "name": "Kanniball Dungeon" },
        { "type": "DJ 186 - 200", "name": "Blightopard Canyon" },
        { "type": "DJ 201 - 215", "name": "Plantiguard Dungeon" },
        { "type": "DJ 216 - 230", "name": "Abyssal Creeper Dungeon" },
        { "type": "DJ 231 - 245", "name": "Timeless Theater Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Larventura" },
        { "type": "Modulox 51 - 95", "name": "Lunar Altar" },
        { "type": "Modulox 96 - 140", "name": "Magik Riktus Den" },
        { "type": "Modulox 141 - 185", "name": "Elite Riktus Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Horridemon Dungeon" }
    ],
    "07/01/2026": [
        { "type": "DJ 6 - 20", "name": "Larventura" },
        { "type": "DJ 21 - 35", "name": "The Raised Vault" },
        { "type": "DJ 36 - 50", "name": "The Hill Hazize" },
        { "type": "DJ 51 - 65", "name": "Bitter-Hammer Dungeon" },
        { "type": "DJ 66 - 80", "name": "Tsu's Palace" },
        { "type": "DJ 81 - 95", "name": "The Undieworld" },
        { "type": "DJ 96 - 110", "name": "Supervillains' Lair" },
        { "type": "DJ 111 - 125", "name": "Tormentor Pit" },
        { "type": "DJ 126 - 140", "name": "Kween's Gawden" },
        { "type": "DJ 141 - 155", "name": "SrambadDungeon" },
        { "type": "DJ 156 - 170", "name": "Mecha Factory" },
        { "type": "DJ 171 - 185", "name": "Forbidden City" },
        { "type": "DJ 186 - 200", "name": "Iced-Over Crest" },
        { "type": "DJ 201 - 215", "name": "Tundrazor Dungeon" },
        { "type": "DJ 216 - 230", "name": "Streye Dungeon?" },
        { "type": "DJ 231 - 245", "name": "Ferociraptor Dungeon" },
        { "type": "Modulox 6 - 50", "name": "The Tofuhouse" },
        { "type": "Modulox 51 - 95", "name": "Dry Selachii" },
        { "type": "Modulox 96 - 140", "name": "Moowolf's Lair" },
        { "type": "Modulox 141 - 185", "name": "Gerbean Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Phytomorph Dungeon" }
    ],
    "08/01/2026": [
        { "type": "DJ 6 - 20", "name": "Gobball Pastures" },
        { "type": "DJ 21 - 35", "name": "Hoola Hoopiwi" },
        { "type": "DJ 36 - 50", "name": "Octopus Crew Dungeon" },
        { "type": "DJ 51 - 65", "name": "Cwab's Castle" },
        { "type": "DJ 66 - 80", "name": "Abandoned Strichery" },
        { "type": "DJ 81 - 95", "name": "Wagnar's Castle" },
        { "type": "DJ 96 - 110", "name": "Jelly Dungeon" },
        { "type": "DJ 111 - 125", "name": "The Snaptrap" },
        { "type": "DJ 126 - 140", "name": "Blackspore Dungeon" },
        { "type": "DJ 141 - 155", "name": "Wa Wabbit's Castle" },
        { "type": "DJ 156 - 170", "name": "Elite Riktus Dungeon" },
        { "type": "DJ 171 - 185", "name": "Crocodyl Dungeon" },
        { "type": "DJ 186 - 200", "name": "The Minerall Tower (lvl 200)" },
        { "type": "DJ 201 - 215", "name": "Scramshell Dungeon" },
        { "type": "DJ 216 - 230", "name": "Destroyer Dungeon" },
        { "type": "DJ 231 - 245", "name": "Primount Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Octopus Crew Dungeon" },
        { "type": "Modulox 51 - 95", "name": "Temple of the Grand Orrok" },
        { "type": "Modulox 96 - 140", "name": "Lenald Empelol's Temple" },
        { "type": "Modulox 141 - 185", "name": "Wellspring of Evil" },
        { "type": "Modulox 186 - 230", "name": "Iced-Over Crest" }
    ],
    "09/01/2026": [
        { "type": "DJ 6 - 20", "name": "The Tofuhouse" },
        { "type": "DJ 21 - 35", "name": "Treechnee Dungeon" },
        { "type": "DJ 36 - 50", "name": "Deathburn Dungeon" },
        { "type": "DJ 51 - 65", "name": "Mollusky Dungeon" },
        { "type": "DJ 66 - 80", "name": "Arachnee Dungeon" },
        { "type": "DJ 81 - 95", "name": "The Undieworld" },
        { "type": "DJ 96 - 110", "name": "Magik Riktus Den" },
        { "type": "DJ 111 - 125", "name": "Ambassador's Wing" },
        { "type": "DJ 126 - 140", "name": "Treechnid Dungeon" },
        { "type": "DJ 141 - 155", "name": "Enurado Dungeon" },
        { "type": "DJ 156 - 170", "name": "Kali's Lair" },
        { "type": "DJ 171 - 185", "name": "Tropickle Dungeon" },
        { "type": "DJ 186 - 200", "name": "Pandala Tomb" },
        { "type": "DJ 201 - 215", "name": "Pingwin Dungeon" },
        { "type": "DJ 216 - 230", "name": "Foggernaut Dungeon" },
        { "type": "DJ 231 - 245", "name": "Starvannah Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Hoola Hoopiwi" },
        { "type": "Modulox 51 - 95", "name": "Bwork Dungeon" },
        { "type": "Modulox 96 - 140", "name": "The Whirlway Station" },
        { "type": "Modulox 141 - 185", "name": "Ow El Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Vandalophrenic Dungeon" }
    ],
    "10/01/2026": [
        { "type": "DJ 6 - 20", "name": "??" },
        { "type": "DJ 21 - 35", "name": "The Raised Vault" },
        { "type": "DJ 36 - 50", "name": "The Royal Pasturizer" },
        { "type": "DJ 51 - 65", "name": "Miss Ugly Tower" },
        { "type": "DJ 66 - 80", "name": "Cro-Cave" },
        { "type": "DJ 81 - 95", "name": "Miseryum" },
        { "type": "DJ 96 - 110", "name": "Dancehall Arena" },
        { "type": "DJ 111 - 125", "name": "The Whirlway Station" },
        { "type": "DJ 126 - 140", "name": "Dirty Trouffe Estate" },
        { "type": "DJ 141 - 155", "name": "Wellspring of Evil" },
        { "type": "DJ 156 - 170", "name": "The Zeppelantern" },
        { "type": "DJ 171 - 185", "name": "Gerbean Dungeon" },
        { "type": "DJ 186 - 200", "name": "Bubourg Factory" },
        { "type": "DJ 201 - 215", "name": "The Mineral Tower (lvl 215)" },
        { "type": "DJ 216 - 230", "name": "Necroworld" },
        { "type": "DJ 231 - 245", "name": "Nox Machine Dungeon" },
        { "type": "Modulox 6 - 50", "name": "The Royal Pasturizer" },
        { "type": "Modulox 51 - 95", "name": "Mussly Hammam" },
        { "type": "Modulox 96 - 140", "name": "Hagen Daz's Pot" },
        { "type": "Modulox 141 - 185", "name": "Bistrogue" },
        { "type": "Modulox 186 - 230", "name": "The Mineral Tower (lvl 215)" }
    ],
    "11/01/2026": [
        { "type": "DJ 6 - 20", "name": "Larventura" },
        { "type": "DJ 21 - 35", "name": "Hoola Hoopiwi" },
        { "type": "DJ 36 - 50", "name": "Sureberry Fields" },
        { "type": "DJ 51 - 65", "name": "Kokokobana" },
        { "type": "DJ 66 - 80", "name": "Boarthroom Estate" },
        { "type": "DJ 81 - 95", "name": "Abandoned Scarapit" },
        { "type": "DJ 96 - 110", "name": "Hushquarters" },
        { "type": "DJ 111 - 125", "name": "Puddly Dungeon" },
        { "type": "DJ 126 - 140", "name": "Lenald Empelol's Temple" },
        { "type": "DJ 141 - 155", "name": "SrambadDungeon" },
        { "type": "DJ 156 - 170", "name": "The Stalagmotel" },
        { "type": "DJ 171 - 185", "name": "Kanniball Dungeon" },
        { "type": "DJ 186 - 200", "name": "Badgeroxes' Lair" },
        { "type": "DJ 201 - 215", "name": "Vandalophrenic Dungeon" },
        { "type": "DJ 216 - 230", "name": "Phytomorph Dungeon" },
        { "type": "DJ 231 - 245", "name": "Timeless Theater Dungeon" },
        { "type": "Modulox 6 - 50", "name": "The Mineral Tower" },
        { "type": "Modulox 51 - 95", "name": "Arachnee Dungeon" },
        { "type": "Modulox 96 - 140", "name": "Flaxhid's Sanctuary" },
        { "type": "Modulox 141 - 185", "name": "Mecha Factory" },
        { "type": "Modulox 186 - 230", "name": "Abyssal Creeper Dungeon" }
    ],
    "12/01/2026": [
        { "type": "DJ 6 - 20", "name": "The Tofuhouse" },
        { "type": "DJ 21 - 35", "name": "Treechnee Dungeon" },
        { "type": "DJ 36 - 50", "name": "Octopus Crew Dungeon" },
        { "type": "DJ 51 - 65", "name": "Dry Selachii" },
        { "type": "DJ 66 - 80", "name": "Tsu's Palace" },
        { "type": "DJ 81 - 95", "name": "Mussly Hammam" },
        { "type": "DJ 96 - 110", "name": "Moowolf's Lair" },
        { "type": "DJ 111 - 125", "name": "Tormentor Pit" },
        { "type": "DJ 126 - 140", "name": "Kween's Gawden" },
        { "type": "DJ 141 - 155", "name": "Abandoned Cawwot Stowewoom" },
        { "type": "DJ 156 - 170", "name": "Mecha Factory" },
        { "type": "DJ 171 - 185", "name": "Tropickle Dungeon" },
        { "type": "DJ 186 - 200", "name": "Blightopard Canyon" },
        { "type": "DJ 201 - 215", "name": "Plantiguard Dungeon" },
        { "type": "DJ 216 - 230", "name": "Abyssal Creeper Dungeon" },
        { "type": "DJ 231 - 245", "name": "Starvannah Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Sureberry Fields" },
        { "type": "Modulox 51 - 95", "name": "Tsu's Palace" },
        { "type": "Modulox 96 - 140", "name": "??" },
        { "type": "Modulox 141 - 185", "name": "Wa Wabbit's Castle" },
        { "type": "Modulox 186 - 230", "name": "Streye Dungeon?" }
    ],
    "13/01/2026": [
        { "type": "DJ 6 - 20", "name": "Gobball Pastures" },
        { "type": "DJ 21 - 35", "name": "The Raised Vault" },
        { "type": "DJ 36 - 50", "name": "The Mineral Tower" },
        { "type": "DJ 51 - 65", "name": "Kokokobana" },
        { "type": "DJ 66 - 80", "name": "Arachnee Dungeon" },
        { "type": "DJ 81 - 95", "name": "Schnekymosis Cavern" },
        { "type": "DJ 96 - 110", "name": "The Horned Glacier" },
        { "type": "DJ 111 - 125", "name": "Hagen Daz's Pot" },
        { "type": "DJ 126 - 140", "name": "Blackspore Dungeon" },
        { "type": "DJ 141 - 155", "name": "The Villainy Vineyards" },
        { "type": "DJ 156 - 170", "name": "Elite Riktus Dungeon" },
        { "type": "DJ 171 - 185", "name": "Kannivore Dungeon" },
        { "type": "DJ 186 - 200", "name": "Badgeroxes' Lair" },
        { "type": "DJ 201 - 215", "name": "Vandalophrenic Dungeon" },
        { "type": "DJ 216 - 230", "name": "Phytomorph Dungeon" },
        { "type": "DJ 231 - 245", "name": "Primount Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Deathburn Dungeon" },
        { "type": "Modulox 51 - 95", "name": "Cwab's Castle" },
        { "type": "Modulox 96 - 140", "name": "Castuc Dungeon" },
        { "type": "Modulox 141 - 185", "name": "The Villainy Vineyards" },
        { "type": "Modulox 186 - 230", "name": "Pingwin Dungeon" }
    ],
    "14/01/2026": [
        { "type": "DJ 6 - 20", "name": "Gobball Pastures" },
        { "type": "DJ 21 - 35", "name": "Hoola Hoopiwi" },
        { "type": "DJ 36 - 50", "name": "The Hill Hazize" },
        { "type": "DJ 51 - 65", "name": "Miss Ugly Tower" },
        { "type": "DJ 66 - 80", "name": "Temple of the Grand Orrok" },
        { "type": "DJ 81 - 95", "name": "Morbax Neplopolis" },
        { "type": "DJ 96 - 110", "name": "Dancehall Arena" },
        { "type": "DJ 111 - 125", "name": "Castuc Dungeon" },
        { "type": "DJ 126 - 140", "name": "Great Zomkin's Compost" },
        { "type": "DJ 141 - 155", "name": "Blopera" },
        { "type": "DJ 156 - 170", "name": "Kali's Lair" },
        { "type": "DJ 171 - 185", "name": "Crocodyl Dungeon" },
        { "type": "DJ 186 - 200", "name": "Bubourg Factory" },
        { "type": "DJ 201 - 215", "name": "The Mineral Tower (lvl 215)" },
        { "type": "DJ 216 - 230", "name": "Necroworld" },
        { "type": "DJ 231 - 245", "name": "Ferociraptor Dungeon" },
        { "type": "Modulox 6 - 50", "name": "The Royal Pasturizer" },
        { "type": "Modulox 51 - 95", "name": "The Undieworld" },
        { "type": "Modulox 96 - 140", "name": "The Horned Glacier" },
        { "type": "Modulox 141 - 185", "name": "Enurado Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Horridemon Dungeon" }
    ],
    "15/01/2026": [
        { "type": "DJ 6 - 20", "name": "The Tofuhouse" },
        { "type": "DJ 21 - 35", "name": "Treechnee Dungeon" },
        { "type": "DJ 36 - 50", "name": "The Royal Pasturizer" },
        { "type": "DJ 51 - 65", "name": "Bwork Dungeon" },
        { "type": "DJ 66 - 80", "name": "Temple of the Grand Orrok" },
        { "type": "DJ 81 - 95", "name": "Trool Academy" },
        { "type": "DJ 96 - 110", "name": "Supervillains' Lair" },
        { "type": "DJ 111 - 125", "name": "The Snaptrap" },
        { "type": "DJ 126 - 140", "name": "Flaxhid's Sanctuary" },
        { "type": "DJ 141 - 155", "name": "Abandoned Cawwot Stowewoom" },
        { "type": "DJ 156 - 170", "name": "The Zeppelantern" },
        { "type": "DJ 171 - 185", "name": "Kanniball Dungeon" },
        { "type": "DJ 186 - 200", "name": "Dreggons' Sanctuary" },
        { "type": "DJ 201 - 215", "name": "Crabstacean Dungeon" },
        { "type": "DJ 216 - 230", "name": "Horridemon Dungeon" },
        { "type": "DJ 231 - 245", "name": "Timeless Theater Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Treechnee Dungeon" },
        { "type": "Modulox 51 - 95", "name": "The Ratatombs" },
        { "type": "Modulox 96 - 140", "name": "Kween's Gawden" },
        { "type": "Modulox 141 - 185", "name": "Forbidden City" },
        { "type": "Modulox 186 - 230", "name": "The Mineral Tower (lvl 215)" }
    ],
    "16/01/2026": [
        { "type": "DJ 6 - 20", "name": "Larventura" },
        { "type": "DJ 21 - 35", "name": "The Raised Vault" },
        { "type": "DJ 36 - 50", "name": "The Mineral Tower" },
        { "type": "DJ 51 - 65", "name": "Bitter-Hammer Dungeon" },
        { "type": "DJ 66 - 80", "name": "Lunar Altar" },
        { "type": "DJ 81 - 95", "name": "Wagnar's Castle" },
        { "type": "DJ 96 - 110", "name": "Hushquarters" },
        { "type": "DJ 111 - 125", "name": "The Frozen Tower" },
        { "type": "DJ 126 - 140", "name": "Lenald Empelol's Temple" },
        { "type": "DJ 141 - 155", "name": "Enurado Dungeon" },
        { "type": "DJ 156 - 170", "name": "The Stalagmotel" },
        { "type": "DJ 171 - 185", "name": "Forbidden City" },
        { "type": "DJ 186 - 200", "name": "Iced-Over Crest" },
        { "type": "DJ 201 - 215", "name": "Tundrazor Dungeon" },
        { "type": "DJ 216 - 230", "name": "Streye Dungeon?" },
        { "type": "DJ 231 - 245", "name": "Starvannah Dungeon" },
        { "type": "Modulox 6 - 50", "name": "The Raised Vault" },
        { "type": "Modulox 51 - 95", "name": "Bitter-Hammer Dungeon" },
        { "type": "Modulox 96 - 140", "name": "Jelly Dungeon" },
        { "type": "Modulox 141 - 185", "name": "Kannivore Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Dreggons' Sanctuary" }
    ],
    "17/01/2026": [
        { "type": "DJ 6 - 20", "name": "Gobball Pastures" },
        { "type": "DJ 21 - 35", "name": "Hoola Hoopiwi" },
        { "type": "DJ 36 - 50", "name": "The Hill Hazize" },
        { "type": "DJ 51 - 65", "name": "The Forgotten Lair" },
        { "type": "DJ 66 - 80", "name": "Abandoned Strichery" },
        { "type": "DJ 81 - 95", "name": "Abandoned Scarapit" },
        { "type": "DJ 96 - 110", "name": "Moowolf's Lair" },
        { "type": "DJ 111 - 125", "name": "Ambassador's Wing" },
        { "type": "DJ 126 - 140", "name": "Dirty Trouffe Estate" },
        { "type": "DJ 141 - 155", "name": "Sandyoptera Mother-Hive" },
        { "type": "DJ 156 - 170", "name": "Mecha Factory" },
        { "type": "DJ 171 - 185", "name": "Gerbean Dungeon" },
        { "type": "DJ 186 - 200", "name": "Or'Hodruin Volcano" },
        { "type": "DJ 201 - 215", "name": "Sunsloth Dungeon" },
        { "type": "DJ 216 - 230", "name": "Voidivion Dungeon" },
        { "type": "DJ 231 - 245", "name": "Ferociraptor Dungeon" },
        { "type": "Modulox 6 - 50", "name": "The Hill Hazize" },
        { "type": "Modulox 51 - 95", "name": "Mollusky Dungeon" },
        { "type": "Modulox 96 - 140", "name": "The Snaptrap" },
        { "type": "Modulox 141 - 185", "name": "Abandoned Cawwot Stowewoom" },
        { "type": "Modulox 186 - 230", "name": "Pingwin Dungeon" }
    ],
    "18/01/2026": [
        { "type": "DJ 6 - 20", "name": "The Tofuhouse" },
        { "type": "DJ 21 - 35", "name": "Treechnee Dungeon" },
        { "type": "DJ 36 - 50", "name": "Octopus Crew Dungeon" },
        { "type": "DJ 51 - 65", "name": "Cwab's Castle" },
        { "type": "DJ 66 - 80", "name": "The Ratatombs" },
        { "type": "DJ 81 - 95", "name": "Miseryum" },
        { "type": "DJ 96 - 110", "name": "The Horned Glacier" },
        { "type": "DJ 111 - 125", "name": "Puddly Dungeon" },
        { "type": "DJ 126 - 140", "name": "Great Zomkin's Compost" },
        { "type": "DJ 141 - 155", "name": "Wellspring of Evil" },
        { "type": "DJ 156 - 170", "name": "Bistrogue" },
        { "type": "DJ 171 - 185", "name": "Kannivore Dungeon" },
        { "type": "DJ 186 - 200", "name": "The Minerall Tower (lvl 200)" },
        { "type": "DJ 201 - 215", "name": "Scramshell Dungeon" },
        { "type": "DJ 216 - 230", "name": "Destroyer Dungeon" },
        { "type": "DJ 231 - 245", "name": "Nox Machine Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Sureberry Fields" },
        { "type": "Modulox 51 - 95", "name": "Miseryum" },
        { "type": "Modulox 96 - 140", "name": "Tormentor Pit" },
        { "type": "Modulox 141 - 185", "name": "Crocodyl Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Tundrazor Dungeon" }
    ],
    "19/01/2026": [
        { "type": "DJ 6 - 20", "name": "??" },
        { "type": "DJ 21 - 35", "name": "The Raised Vault" },
        { "type": "DJ 36 - 50", "name": "Deathburn Dungeon" },
        { "type": "DJ 51 - 65", "name": "Mollusky Dungeon" },
        { "type": "DJ 66 - 80", "name": "Lunar Altar" },
        { "type": "DJ 81 - 95", "name": "Wagnar's Castle" },
        { "type": "DJ 96 - 110", "name": "Jelly Dungeon" },
        { "type": "DJ 111 - 125", "name": "The Snaptrap" },
        { "type": "DJ 126 - 140", "name": "Kween's Gawden" },
        { "type": "DJ 141 - 155", "name": "Wa Wabbit's Castle" },
        { "type": "DJ 156 - 170", "name": "Ow El Dungeon" },
        { "type": "DJ 171 - 185", "name": "Gerbean Dungeon" },
        { "type": "DJ 186 - 200", "name": "Pandala Tomb" },
        { "type": "DJ 201 - 215", "name": "Pingwin Dungeon" },
        { "type": "DJ 216 - 230", "name": "Foggernaut Dungeon" },
        { "type": "DJ 231 - 245", "name": "Bworkana Clan Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Deathburn Dungeon" },
        { "type": "Modulox 51 - 95", "name": "Cro-Cave" },
        { "type": "Modulox 96 - 140", "name": "Blackspore Dungeon" },
        { "type": "Modulox 141 - 185", "name": "Tropickle Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Dreggons' Sanctuary" }
    ],
    "20/01/2026": [
        { "type": "DJ 6 - 20", "name": "Larventura" },
        { "type": "DJ 21 - 35", "name": "Hoola Hoopiwi" },
        { "type": "DJ 36 - 50", "name": "The Royal Pasturizer" },
        { "type": "DJ 51 - 65", "name": "Bwork Dungeon" },
        { "type": "DJ 66 - 80", "name": "Boarthroom Estate" },
        { "type": "DJ 81 - 95", "name": "Schnekymosis Cavern" },
        { "type": "DJ 96 - 110", "name": "Magik Riktus Den" },
        { "type": "DJ 111 - 125", "name": "Tormentor Pit" },
        { "type": "DJ 126 - 140", "name": "Flaxhid's Sanctuary" },
        { "type": "DJ 141 - 155", "name": "Blopera" },
        { "type": "DJ 156 - 170", "name": "The Zeppelantern" },
        { "type": "DJ 171 - 185", "name": "Crocodyl Dungeon" },
        { "type": "DJ 186 - 200", "name": "Dreggons' Sanctuary" },
        { "type": "DJ 201 - 215", "name": "Crabstacean Dungeon" },
        { "type": "DJ 216 - 230", "name": "Horridemon Dungeon" },
        { "type": "DJ 231 - 245", "name": "Primount Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Larventura" },
        { "type": "Modulox 51 - 95", "name": "Bwork Dungeon" },
        { "type": "Modulox 96 - 140", "name": "Puddly Dungeon" },
        { "type": "Modulox 141 - 185", "name": "SrambadDungeon" },
        { "type": "Modulox 186 - 230", "name": "Badgeroxes' Lair" }
    ],
    "21/01/2026": [
        { "type": "DJ 6 - 20", "name": "The Tofuhouse" },
        { "type": "DJ 21 - 35", "name": "Treechnee Dungeon" },
        { "type": "DJ 36 - 50", "name": "Sureberry Fields" },
        { "type": "DJ 51 - 65", "name": "Dry Selachii" },
        { "type": "DJ 66 - 80", "name": "Cro-Cave" },
        { "type": "DJ 81 - 95", "name": "Mussly Hammam" },
        { "type": "DJ 96 - 110", "name": "Dancehall Arena" },
        { "type": "DJ 111 - 125", "name": "Castuc Dungeon" },
        { "type": "DJ 126 - 140", "name": "Treechnid Dungeon" },
        { "type": "DJ 141 - 155", "name": "The Villainy Vineyards" },
        { "type": "DJ 156 - 170", "name": "Kali's Lair" },
        { "type": "DJ 171 - 185", "name": "Forbidden City" },
        { "type": "DJ 186 - 200", "name": "Blightopard Canyon" },
        { "type": "DJ 201 - 215", "name": "Plantiguard Dungeon" },
        { "type": "DJ 216 - 230", "name": "Abyssal Creeper Dungeon" },
        { "type": "DJ 231 - 245", "name": "Bworkana Clan Dungeon" },
        { "type": "Modulox 6 - 50", "name": "The Mineral Tower" },
        { "type": "Modulox 51 - 95", "name": "Wagnar's Castle" },
        { "type": "Modulox 96 - 140", "name": "Lenald Empelol's Temple" },
        { "type": "Modulox 141 - 185", "name": "Blopera" },
        { "type": "Modulox 186 - 230", "name": "Necroworld" }
    ],
    "22/01/2026": [
        { "type": "DJ 6 - 20", "name": "Gobball Pastures" },
        { "type": "DJ 21 - 35", "name": "The Raised Vault" },
        { "type": "DJ 36 - 50", "name": "Octopus Crew Dungeon" },
        { "type": "DJ 51 - 65", "name": "Bitter-Hammer Dungeon" },
        { "type": "DJ 66 - 80", "name": "Arachnee Dungeon" },
        { "type": "DJ 81 - 95", "name": "Morbax Neplopolis" },
        { "type": "DJ 96 - 110", "name": "Hushquarters" },
        { "type": "DJ 111 - 125", "name": "Hagen Daz's Pot" },
        { "type": "DJ 126 - 140", "name": "Dirty Trouffe Estate" },
        { "type": "DJ 141 - 155", "name": "Sandyoptera Mother-Hive" },
        { "type": "DJ 156 - 170", "name": "Bistrogue" },
        { "type": "DJ 171 - 185", "name": "Kannivore Dungeon" },
        { "type": "DJ 186 - 200", "name": "Iced-Over Crest" },
        { "type": "DJ 201 - 215", "name": "Tundrazor Dungeon" },
        { "type": "DJ 216 - 230", "name": "Streye Dungeon?" },
        { "type": "DJ 231 - 245", "name": "Nox Machine Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Octopus Crew Dungeon" },
        { "type": "Modulox 51 - 95", "name": "Boarthroom Estate" },
        { "type": "Modulox 96 - 140", "name": "Ambassador's Wing" },
        { "type": "Modulox 141 - 185", "name": "Kanniball Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Destroyer Dungeon" }
    ],
    "23/01/2026": [
        { "type": "DJ 6 - 20", "name": "Gobball Pastures" },
        { "type": "DJ 21 - 35", "name": "Hoola Hoopiwi" },
        { "type": "DJ 36 - 50", "name": "The Mineral Tower" },
        { "type": "DJ 51 - 65", "name": "The Forgotten Lair" },
        { "type": "DJ 66 - 80", "name": "The Ratatombs" },
        { "type": "DJ 81 - 95", "name": "Trool Academy" },
        { "type": "DJ 96 - 110", "name": "Moowolf's Lair" },
        { "type": "DJ 111 - 125", "name": "The Whirlway Station" },
        { "type": "DJ 126 - 140", "name": "Blackspore Dungeon" },
        { "type": "DJ 141 - 155", "name": "SrambadDungeon" },
        { "type": "DJ 156 - 170", "name": "The Stalagmotel" },
        { "type": "DJ 171 - 185", "name": "Tropickle Dungeon" },
        { "type": "DJ 186 - 200", "name": "Or'Hodruin Volcano" },
        { "type": "DJ 201 - 215", "name": "Sunsloth Dungeon" },
        { "type": "DJ 216 - 230", "name": "Voidivion Dungeon" },
        { "type": "DJ 231 - 245", "name": "Timeless Theater Dungeon" },
        { "type": "Modulox 6 - 50", "name": "The Hill Hazize" },
        { "type": "Modulox 51 - 95", "name": "Bitter-Hammer Dungeon" },
        { "type": "Modulox 96 - 140", "name": "Moowolf's Lair" },
        { "type": "Modulox 141 - 185", "name": "Elite Riktus Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Vandalophrenic Dungeon" }
    ],
    "24/01/2026": [
        { "type": "DJ 6 - 20", "name": "The Tofuhouse" },
        { "type": "DJ 21 - 35", "name": "Treechnee Dungeon" },
        { "type": "DJ 36 - 50", "name": "The Hill Hazize" },
        { "type": "DJ 51 - 65", "name": "Miss Ugly Tower" },
        { "type": "DJ 66 - 80", "name": "Tsu's Palace" },
        { "type": "DJ 81 - 95", "name": "The Undieworld" },
        { "type": "DJ 96 - 110", "name": "The Horned Glacier" },
        { "type": "DJ 111 - 125", "name": "The Frozen Tower" },
        { "type": "DJ 126 - 140", "name": "Great Zomkin's Compost" },
        { "type": "DJ 141 - 155", "name": "Wa Wabbit's Castle" },
        { "type": "DJ 156 - 170", "name": "Ow El Dungeon" },
        { "type": "DJ 171 - 185", "name": "Kanniball Dungeon" },
        { "type": "DJ 186 - 200", "name": "Bubourg Factory" },
        { "type": "DJ 201 - 215", "name": "The Mineral Tower (lvl 215)" },
        { "type": "DJ 216 - 230", "name": "Necroworld" },
        { "type": "DJ 231 - 245", "name": "Ferociraptor Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Hoola Hoopiwi" },
        { "type": "Modulox 51 - 95", "name": "The Forgotten Lair" },
        { "type": "Modulox 96 - 140", "name": "Treechnid Dungeon" },
        { "type": "Modulox 141 - 185", "name": "Gerbean Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Plantiguard Dungeon" }
    ],
    "25/01/2026": [
        { "type": "DJ 6 - 20", "name": "Larventura" },
        { "type": "DJ 21 - 35", "name": "The Raised Vault" },
        { "type": "DJ 36 - 50", "name": "The Royal Pasturizer" },
        { "type": "DJ 51 - 65", "name": "Bwork Dungeon" },
        { "type": "DJ 66 - 80", "name": "Abandoned Strichery" },
        { "type": "DJ 81 - 95", "name": "Wagnar's Castle" },
        { "type": "DJ 96 - 110", "name": "Dancehall Arena" },
        { "type": "DJ 111 - 125", "name": "The Whirlway Station" },
        { "type": "DJ 126 - 140", "name": "Flaxhid's Sanctuary" },
        { "type": "DJ 141 - 155", "name": "Enurado Dungeon" },
        { "type": "DJ 156 - 170", "name": "Elite Riktus Dungeon" },
        { "type": "DJ 171 - 185", "name": "Forbidden City" },
        { "type": "DJ 186 - 200", "name": "Dreggons' Sanctuary" },
        { "type": "DJ 201 - 215", "name": "Crabstacean Dungeon" },
        { "type": "DJ 216 - 230", "name": "Horridemon Dungeon" },
        { "type": "DJ 231 - 245", "name": "Primount Dungeon" },
        { "type": "Modulox 6 - 50", "name": "The Tofuhouse" },
        { "type": "Modulox 51 - 95", "name": "Morbax Neplopolis" },
        { "type": "Modulox 96 - 140", "name": "The Frozen Tower" },
        { "type": "Modulox 141 - 185", "name": "The Zeppelantern" },
        { "type": "Modulox 186 - 230", "name": "Scramshell Dungeon" }
    ],
    "26/01/2026": [
        { "type": "DJ 6 - 20", "name": "Gobball Pastures" },
        { "type": "DJ 21 - 35", "name": "Hoola Hoopiwi" },
        { "type": "DJ 36 - 50", "name": "The Mineral Tower" },
        { "type": "DJ 51 - 65", "name": "Kokokobana" },
        { "type": "DJ 66 - 80", "name": "Temple of the Grand Orrok" },
        { "type": "DJ 81 - 95", "name": "The Undieworld" },
        { "type": "DJ 96 - 110", "name": "Supervillains' Lair" },
        { "type": "DJ 111 - 125", "name": "Hagen Daz's Pot" },
        { "type": "DJ 126 - 140", "name": "Treechnid Dungeon" },
        { "type": "DJ 141 - 155", "name": "Wellspring of Evil" },
        { "type": "DJ 156 - 170", "name": "The Zeppelantern" },
        { "type": "DJ 171 - 185", "name": "Crocodyl Dungeon" },
        { "type": "DJ 186 - 200", "name": "Badgeroxes' Lair" },
        { "type": "DJ 201 - 215", "name": "Vandalophrenic Dungeon" },
        { "type": "DJ 216 - 230", "name": "Phytomorph Dungeon" },
        { "type": "DJ 231 - 245", "name": "Starvannah Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Gobball Pastures" },
        { "type": "Modulox 51 - 95", "name": "Mussly Hammam" },
        { "type": "Modulox 96 - 140", "name": "Jelly Dungeon" },
        { "type": "Modulox 141 - 185", "name": "Blopera" },
        { "type": "Modulox 186 - 230", "name": "Necroworld" }
    ],
    "27/01/2026": [
        { "type": "DJ 6 - 20", "name": "The Tofuhouse" },
        { "type": "DJ 21 - 35", "name": "Treechnee Dungeon" },
        { "type": "DJ 36 - 50", "name": "The Hill Hazize" },
        { "type": "DJ 51 - 65", "name": "Cwab's Castle" },
        { "type": "DJ 66 - 80", "name": "Lunar Altar" },
        { "type": "DJ 81 - 95", "name": "Miseryum" },
        { "type": "DJ 96 - 110", "name": "Hushquarters" },
        { "type": "DJ 111 - 125", "name": "The Frozen Tower" },
        { "type": "DJ 126 - 140", "name": "Lenald Empelol's Temple" },
        { "type": "DJ 141 - 155", "name": "SrambadDungeon" },
        { "type": "DJ 156 - 170", "name": "The Stalagmotel" },
        { "type": "DJ 171 - 185", "name": "Tropickle Dungeon" },
        { "type": "DJ 186 - 200", "name": "The Minerall Tower (lvl 200)" },
        { "type": "DJ 201 - 215", "name": "Scramshell Dungeon" },
        { "type": "DJ 216 - 230", "name": "Destroyer Dungeon" },
        { "type": "DJ 231 - 245", "name": "Nox Machine Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Larventura" },
        { "type": "Modulox 51 - 95", "name": "Tsu's Palace" },
        { "type": "Modulox 96 - 140", "name": "Kween's Gawden" },
        { "type": "Modulox 141 - 185", "name": "Ow El Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Plantiguard Dungeon" }
    ],
    "28/01/2026": [
        { "type": "DJ 6 - 20", "name": "??" },
        { "type": "DJ 21 - 35", "name": "The Raised Vault" },
        { "type": "DJ 36 - 50", "name": "Octopus Crew Dungeon" },
        { "type": "DJ 51 - 65", "name": "Mollusky Dungeon" },
        { "type": "DJ 66 - 80", "name": "The Ratatombs" },
        { "type": "DJ 81 - 95", "name": "Abandoned Scarapit" },
        { "type": "DJ 96 - 110", "name": "Moowolf's Lair" },
        { "type": "DJ 111 - 125", "name": "Puddly Dungeon" },
        { "type": "DJ 126 - 140", "name": "Kween's Gawden" },
        { "type": "DJ 141 - 155", "name": "Abandoned Cawwot Stowewoom" },
        { "type": "DJ 156 - 170", "name": "Mecha Factory" },
        { "type": "DJ 171 - 185", "name": "Gerbean Dungeon" },
        { "type": "DJ 186 - 200", "name": "Pandala Tomb" },
        { "type": "DJ 201 - 215", "name": "Pingwin Dungeon" },
        { "type": "DJ 216 - 230", "name": "Foggernaut Dungeon" },
        { "type": "DJ 231 - 245", "name": "Timeless Theater Dungeon" },
        { "type": "Modulox 6 - 50", "name": "The Mineral Tower" },
        { "type": "Modulox 51 - 95", "name": "Trool Academy" },
        { "type": "Modulox 96 - 140", "name": "Magik Riktus Den" },
        { "type": "Modulox 141 - 185", "name": "The Villainy Vineyards" },
        { "type": "Modulox 186 - 230", "name": "Blightopard Canyon" }
    ],
    "29/01/2026": [
        { "type": "DJ 6 - 20", "name": "Larventura" },
        { "type": "DJ 21 - 35", "name": "Hoola Hoopiwi" },
        { "type": "DJ 36 - 50", "name": "Deathburn Dungeon" },
        { "type": "DJ 51 - 65", "name": "The Forgotten Lair" },
        { "type": "DJ 66 - 80", "name": "Cro-Cave" },
        { "type": "DJ 81 - 95", "name": "Mussly Hammam" },
        { "type": "DJ 96 - 110", "name": "The Horned Glacier" },
        { "type": "DJ 111 - 125", "name": "Ambassador's Wing" },
        { "type": "DJ 126 - 140", "name": "Blackspore Dungeon" },
        { "type": "DJ 141 - 155", "name": "The Villainy Vineyards" },
        { "type": "DJ 156 - 170", "name": "Elite Riktus Dungeon" },
        { "type": "DJ 171 - 185", "name": "Kanniball Dungeon" },
        { "type": "DJ 186 - 200", "name": "Or'Hodruin Volcano" },
        { "type": "DJ 201 - 215", "name": "Sunsloth Dungeon" },
        { "type": "DJ 216 - 230", "name": "Voidivion Dungeon" },
        { "type": "DJ 231 - 245", "name": "Starvannah Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Octopus Crew Dungeon" },
        { "type": "Modulox 51 - 95", "name": "Mussly Hammam" },
        { "type": "Modulox 96 - 140", "name": "Hushquarters" },
        { "type": "Modulox 141 - 185", "name": "Enurado Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Sunsloth Dungeon" }
    ],
    "30/01/2026": [
        { "type": "DJ 6 - 20", "name": "The Tofuhouse" },
        { "type": "DJ 21 - 35", "name": "Treechnee Dungeon" },
        { "type": "DJ 36 - 50", "name": "The Royal Pasturizer" },
        { "type": "DJ 51 - 65", "name": "Dry Selachii" },
        { "type": "DJ 66 - 80", "name": "Boarthroom Estate" },
        { "type": "DJ 81 - 95", "name": "Schnekymosis Cavern" },
        { "type": "DJ 96 - 110", "name": "Jelly Dungeon" },
        { "type": "DJ 111 - 125", "name": "Castuc Dungeon" },
        { "type": "DJ 126 - 140", "name": "Great Zomkin's Compost" },
        { "type": "DJ 141 - 155", "name": "Blopera" },
        { "type": "DJ 156 - 170", "name": "Kali's Lair" },
        { "type": "DJ 171 - 185", "name": "Tropickle Dungeon" },
        { "type": "DJ 186 - 200", "name": "Blightopard Canyon" },
        { "type": "DJ 201 - 215", "name": "The Mineral Tower (lvl 215)" },
        { "type": "DJ 216 - 230", "name": "Abyssal Creeper Dungeon" },
        { "type": "DJ 231 - 245", "name": "Primount Dungeon" },
        { "type": "Modulox 6 - 50", "name": "The Hill Hazize" },
        { "type": "Modulox 51 - 95", "name": "Kokokobana" },
        { "type": "Modulox 96 - 140", "name": "Great Zomkin's Compost" },
        { "type": "Modulox 141 - 185", "name": "Bistrogue" },
        { "type": "Modulox 186 - 230", "name": "Or'Hodruin Volcano" }
    ],
    "31/01/2026": [
        { "type": "DJ 6 - 20", "name": "Gobball Pastures" },
        { "type": "DJ 21 - 35", "name": "The Raised Vault" },
        { "type": "DJ 36 - 50", "name": "Sureberry Fields" },
        { "type": "DJ 51 - 65", "name": "Bitter-Hammer Dungeon" },
        { "type": "DJ 66 - 80", "name": "Tsu's Palace" },
        { "type": "DJ 81 - 95", "name": "Morbax Neplopolis" },
        { "type": "DJ 96 - 110", "name": "Magik Riktus Den" },
        { "type": "DJ 111 - 125", "name": "Tormentor Pit" },
        { "type": "DJ 126 - 140", "name": "Flaxhid's Sanctuary" },
        { "type": "DJ 141 - 155", "name": "Sandyoptera Mother-Hive" },
        { "type": "DJ 156 - 170", "name": "The Zeppelantern" },
        { "type": "DJ 171 - 185", "name": "Kannivore Dungeon" },
        { "type": "DJ 186 - 200", "name": "Dreggons' Sanctuary" },
        { "type": "DJ 201 - 215", "name": "Crabstacean Dungeon" },
        { "type": "DJ 216 - 230", "name": "Streye Dungeon?" },
        { "type": "DJ 231 - 245", "name": "Ferociraptor Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Hoola Hoopiwi" },
        { "type": "Modulox 51 - 95", "name": "Abandoned Scarapit" },
        { "type": "Modulox 96 - 140", "name": "Castuc Dungeon" },
        { "type": "Modulox 141 - 185", "name": "The Zeppelantern" },
        { "type": "Modulox 186 - 230", "name": "Vandalophrenic Dungeon" }
    ],
    "01/02/2026": [
        { "type": "DJ 6 - 20", "name": "Gobball Pastures" },
        { "type": "DJ 21 - 35", "name": "Hoola Hoopiwi" },
        { "type": "DJ 36 - 50", "name": "The Mineral Tower" },
        { "type": "DJ 51 - 65", "name": "Cwab's Castle" },
        { "type": "DJ 66 - 80", "name": "Abandoned Strichery" },
        { "type": "DJ 81 - 95", "name": "Trool Academy" },
        { "type": "DJ 96 - 110", "name": "Dancehall Arena" },
        { "type": "DJ 111 - 125", "name": "The Snaptrap" },
        { "type": "DJ 126 - 140", "name": "Treechnid Dungeon" },
        { "type": "DJ 141 - 155", "name": "SrambadDungeon" },
        { "type": "DJ 156 - 170", "name": "The Stalagmotel" },
        { "type": "DJ 171 - 185", "name": "Crocodyl Dungeon" },
        { "type": "DJ 186 - 200", "name": "Iced-Over Crest" },
        { "type": "DJ 201 - 215", "name": "Tundrazor Dungeon" },
        { "type": "DJ 216 - 230", "name": "Destroyer Dungeon" },
        { "type": "DJ 231 - 245", "name": "Timeless Theater Dungeon" },
        { "type": "Modulox 6 - 50", "name": "The Tofuhouse" },
        { "type": "Modulox 51 - 95", "name": "Schnekymosis Cavern" },
        { "type": "Modulox 96 - 140", "name": "The Snaptrap" },
        { "type": "Modulox 141 - 185", "name": "Sandyoptera Mother-Hive" },
        { "type": "Modulox 186 - 230", "name": "Iced-Over Crest" }
    ],
    "02/02/2026": [
        { "type": "DJ 6 - 20", "name": "The Tofuhouse" },
        { "type": "DJ 21 - 35", "name": "Treechnee Dungeon" },
        { "type": "DJ 36 - 50", "name": "Octopus Crew Dungeon" },
        { "type": "DJ 51 - 65", "name": "Mollusky Dungeon" },
        { "type": "DJ 66 - 80", "name": "Arachnee Dungeon" },
        { "type": "DJ 81 - 95", "name": "The Undieworld" },
        { "type": "DJ 96 - 110", "name": "Hushquarters" },
        { "type": "DJ 111 - 125", "name": "Ambassador's Wing" },
        { "type": "DJ 126 - 140", "name": "Lenald Empelol's Temple" },
        { "type": "DJ 141 - 155", "name": "Wa Wabbit's Castle" },
        { "type": "DJ 156 - 170", "name": "Mecha Factory" },
        { "type": "DJ 171 - 185", "name": "Kanniball Dungeon" },
        { "type": "DJ 186 - 200", "name": "The Minerall Tower (lvl 200)" },
        { "type": "DJ 201 - 215", "name": "Scramshell Dungeon" },
        { "type": "DJ 216 - 230", "name": "Foggernaut Dungeon" },
        { "type": "DJ 231 - 245", "name": "Starvannah Dungeon" },
        { "type": "Modulox 6 - 50", "name": "Gobball Pastures" },
        { "type": "Modulox 51 - 95", "name": "Mollusky Dungeon" },
        { "type": "Modulox 96 - 140", "name": "The Whirlway Station" },
        { "type": "Modulox 141 - 185", "name": "Kali's Lair" },
        { "type": "Modulox 186 - 230", "name": "Destroyer Dungeon" }
    ],
    "03/02/2026": [
        { "type": "DJ 6 - 20", "name": "Larventura" },
        { "type": "DJ 21 - 35", "name": "The Raised Vault" },
        { "type": "DJ 36 - 50", "name": "Deathburn Dungeon" },
        { "type": "DJ 51 - 65", "name": "Miss Ugly Tower" },
        { "type": "DJ 66 - 80", "name": "Cro-Cave" },
        { "type": "DJ 81 - 95", "name": "Wagnar's Castle" },
        { "type": "DJ 96 - 110", "name": "Moowolf's Lair" },
        { "type": "DJ 111 - 125", "name": "The Whirlway Station" },
        { "type": "DJ 126 - 140", "name": "Kween's Gawden" },
        { "type": "DJ 141 - 155", "name": "Enurado Dungeon" },
        { "type": "DJ 156 - 170", "name": "Elite Riktus Dungeon" },
        { "type": "DJ 171 - 185", "name": "Forbidden City" },
        { "type": "DJ 186 - 200", "name": "Pandala Tomb" },
        { "type": "DJ 201 - 215", "name": "Pingwin Dungeon" },
        { "type": "DJ 216 - 230", "name": "Necroworld" },
        { "type": "DJ 231 - 245", "name": "Ferociraptor Dungeon" },
        { "type": "Modulox 6 - 50", "name": "" },
        { "type": "Modulox 51 - 95", "name": "Lunar Altar" },
        { "type": "Modulox 96 - 140", "name": "Hagen Daz's Pot" },
        { "type": "Modulox 141 - 185", "name": "Kannivore Dungeon" },
        { "type": "Modulox 186 - 230", "name": "The Minerall Tower (lvl 200)" }
    ],
    "04/02/2026": [
        { "type": "DJ 6 - 20", "name": "Gobball Pastures" },
        { "type": "DJ 21 - 35", "name": "Hoola Hoopiwi" },
        { "type": "DJ 36 - 50", "name": "The Royal Pasturizer" },
        { "type": "DJ 51 - 65", "name": "Kokokobana" },
        { "type": "DJ 66 - 80", "name": "Boarthroom Estate" },
        { "type": "DJ 81 - 95", "name": "The Undieworld" },
        { "type": "DJ 96 - 110", "name": "The Horned Glacier" },
        { "type": "DJ 111 - 125", "name": "Puddly Dungeon" },
        { "type": "DJ 126 - 140", "name": "Blackspore Dungeon" },
        { "type": "DJ 141 - 155", "name": "Wellspring of Evil" },
        { "type": "DJ 156 - 170", "name": "The Zeppelantern" },
        { "type": "DJ 171 - 185", "name": "Gerbean Dungeon" },
        { "type": "DJ 186 - 200", "name": "Bubourg Factory" },
        { "type": "DJ 201 - 215", "name": "The Mineral Tower (lvl 215)" },
        { "type": "DJ 216 - 230", "name": "Phytomorph Dungeon" },
        { "type": "DJ 231 - 245", "name": "Nox Machine Dungeon" },
        { "type": "Modulox 6 - 50", "name": "" },
        { "type": "Modulox 51 - 95", "name": "The Undieworld" },
        { "type": "Modulox 96 - 140", "name": "Great Zomkin's Compost" },
        { "type": "Modulox 141 - 185", "name": "The Zeppelantern" },
        { "type": "Modulox 186 - 230", "name": "Voidivion Dungeon" }
    ],
    "05/02/2026": [
        { "type": "DJ 6 - 20", "name": "The Tofuhouse" },
        { "type": "DJ 21 - 35", "name": "Treechnee Dungeon" },
        { "type": "DJ 36 - 50", "name": "Sureberry Fields" },
        { "type": "DJ 51 - 65", "name": "Dry Selachii" },
        { "type": "DJ 66 - 80", "name": "Tsu's Palace" },
        { "type": "DJ 81 - 95", "name": "Miseryum" },
        { "type": "DJ 96 - 110", "name": "Jelly Dungeon" },
        { "type": "DJ 111 - 125", "name": "Tormentor Pit" },
        { "type": "DJ 126 - 140", "name": "Great Zomkin's Compost" },
        { "type": "DJ 141 - 155", "name": "SrambadDungeon" },
        { "type": "DJ 156 - 170", "name": "The Stalagmotel" },
        { "type": "DJ 171 - 185", "name": "Kannivore Dungeon" },
        { "type": "DJ 186 - 200", "name": "Badgeroxes' Lair" },
        { "type": "DJ 201 - 215", "name": "Vandalophrenic Dungeon" },
        { "type": "DJ 216 - 230", "name": "Abyssal Creeper Dungeon" },
        { "type": "DJ 231 - 245", "name": "Bworkana Clan Dungeon" },
        { "type": "Modulox 6 - 50", "name": "" },
        { "type": "Modulox 51 - 95", "name": "Arachnee Dungeon" },
        { "type": "Modulox 96 - 140", "name": "Dancehall Arena" },
        { "type": "Modulox 141 - 185", "name": "Bistrogue" },
        { "type": "Modulox 186 - 230", "name": "Phytomorph Dungeon" }
    ],
    "06/02/2026": [
        { "type": "DJ 6 - 20", "name": "??" },
        { "type": "DJ 21 - 35", "name": "The Raised Vault" },
        { "type": "DJ 36 - 50", "name": "Octopus Crew Dungeon" },
        { "type": "DJ 51 - 65", "name": "Kokokobana" },
        { "type": "DJ 66 - 80", "name": "Arachnee Dungeon" },
        { "type": "DJ 81 - 95", "name": "Abandoned Scarapit" },
        { "type": "DJ 96 - 110", "name": "Magik Riktus Den" },
        { "type": "DJ 111 - 125", "name": "Hagen Daz's Pot" },
        { "type": "DJ 126 - 140", "name": "Flaxhid's Sanctuary" },
        { "type": "DJ 141 - 155", "name": "Abandoned Cawwot Stowewoom" },
        { "type": "DJ 156 - 170", "name": "Mecha Factory" },
        { "type": "DJ 171 - 185", "name": "Gerbean Dungeon" },
        { "type": "DJ 186 - 200", "name": "Blightopard Canyon" },
        { "type": "DJ 201 - 215", "name": "Plantiguard Dungeon" },
        { "type": "DJ 216 - 230", "name": "Phytomorph Dungeon" },
        { "type": "DJ 231 - 245", "name": "Primount Dungeon" },
        { "type": "Modulox 6 - 50", "name": "" },
        { "type": "Modulox 51 - 95", "name": "Schnekymosis Cavern" },
        { "type": "Modulox 96 - 140", "name": "Flaxhid's Sanctuary" },
        { "type": "Modulox 141 - 185", "name": "Mecha Factory" },
        { "type": "Modulox 186 - 230", "name": "The Mineral Tower (lvl 215)" }
    ],
    "07/02/2026": [
        { "type": "DJ 6 - 20", "name": "Larventura" },
        { "type": "DJ 21 - 35", "name": "Hoola Hoopiwi" },
        { "type": "DJ 36 - 50", "name": "The Royal Pasturizer" },
        { "type": "DJ 51 - 65", "name": "Miss Ugly Tower" },
        { "type": "DJ 66 - 80", "name": "Temple of the Grand Orrok" },
        { "type": "DJ 81 - 95", "name": "Mussly Hammam" },
        { "type": "DJ 96 - 110", "name": "Hushquarters" },
        { "type": "DJ 111 - 125", "name": "The Whirlway Station" },
        { "type": "DJ 126 - 140", "name": "Lenald Empelol's Temple" },
        { "type": "DJ 141 - 155", "name": "The Villainy Vineyards" },
        { "type": "DJ 156 - 170", "name": "Elite Riktus Dungeon" },
        { "type": "DJ 171 - 185", "name": "Crocodyl Dungeon" },
        { "type": "DJ 186 - 200", "name": "Badgeroxes' Lair" },
        { "type": "DJ 201 - 215", "name": "Vandalophrenic Dungeon" },
        { "type": "DJ 216 - 230", "name": "Necroworld" },
        { "type": "DJ 231 - 245", "name": "Bworkana Clan Dungeon" },
        { "type": "Modulox 6 - 50", "name": "" },
        { "type": "Modulox 51 - 95", "name": "Trool Academy" },
        { "type": "Modulox 96 - 140", "name": "Tormentor Pit" },
        { "type": "Modulox 141 - 185", "name": "Crocodyl Dungeon" },
        { "type": "Modulox 186 - 230", "name": "Foggernaut Dungeon" }
    ],
    "08/02/2026": [
        { "type": "DJ 6 - 20", "name": "The Tofuhouse" },
        { "type": "DJ 21 - 35", "name": "Treechnee Dungeon" },
        { "type": "DJ 36 - 50", "name": "Deathburn Dungeon" },
        { "type": "DJ 51 - 65", "name": "Bwork Dungeon" },
        { "type": "DJ 66 - 80", "name": "Temple of the Grand Orrok" },
        { "type": "DJ 81 - 95", "name": "Schnekymosis Cavern" },
        { "type": "DJ 96 - 110", "name": "Supervillains' Lair" },
        { "type": "DJ 111 - 125", "name": "The Frozen Tower" },
        { "type": "DJ 126 - 140", "name": "Dirty Trouffe Estate" },
        { "type": "DJ 141 - 155", "name": "Blopera" },
        { "type": "DJ 156 - 170", "name": "The Zeppelantern" },
        { "type": "DJ 171 - 185", "name": "Forbidden City" },
        { "type": "DJ 186 - 200", "name": "Bubourg Factory" },
        { "type": "DJ 201 - 215", "name": "The Mineral Tower (lvl 215)" },
        { "type": "DJ 216 - 230", "name": "Horridemon Dungeon" },
        { "type": "DJ 231 - 245", "name": "Nox Machine Dungeon" },
        { "type": "Modulox 6 - 50", "name": "" },
        { "type": "Modulox 51 - 95", "name": "The Ratatombs" },
        { "type": "Modulox 96 - 140", "name": "Dirty Trouffe Estate" },
        { "type": "Modulox 141 - 185", "name": "Forbidden City" },
        { "type": "Modulox 186 - 230", "name": "Crabstacean Dungeon" }
    ],
    "09/02/2026": [
        { "type": "DJ 6 - 20", "name": "Gobball Pastures" },
        { "type": "DJ 21 - 35", "name": "The Raised Vault" },
        { "type": "DJ 36 - 50", "name": "Sureberry Fields" },
        { "type": "DJ 51 - 65", "name": "Bitter-Hammer Dungeon" },
        { "type": "DJ 66 - 80", "name": "Lunar Altar" },
        { "type": "DJ 81 - 95", "name": "Trool Academy" },
        { "type": "DJ 96 - 110", "name": "Jelly Dungeon" },
        { "type": "DJ 111 - 125", "name": "The Whirlway Station" },
        { "type": "DJ 126 - 140", "name": "Great Zomkin's Compost" },
        { "type": "DJ 141 - 155", "name": "Abandoned Cawwot Stowewoom" },
        { "type": "DJ 156 - 170", "name": "The Stalagmotel" },
        { "type": "DJ 171 - 185", "name": "Kannivore Dungeon" },
        { "type": "DJ 186 - 200", "name": "Dreggons' Sanctuary" },
        { "type": "DJ 201 - 215", "name": "Crabstacean Dungeon" },
        { "type": "DJ 216 - 230", "name": "Streye Dungeon?" },
        { "type": "DJ 231 - 245", "name": "" },
        { "type": "Modulox 6 - 50", "name": "" },
        { "type": "Modulox 51 - 95", "name": "Cwab's Castle" },
        { "type": "Modulox 96 - 140", "name": "Puddly Dungeon" },
        { "type": "Modulox 141 - 185", "name": "Kali's Lair" },
        { "type": "Modulox 186 - 230", "name": "Abyssal Creeper Dungeon" }
    ]
};